# pnpm workspace configuration
# Defines packages in the monorepo and shared dependency versions via catalog

packages:
  - '.'
  - 'servers/autopilot/deploy'

catalog:
  # TypeScript tooling
  typescript: ^5.5.2
  tsx: ^4.19.2
  ts-node: ^10.9.1

  # Testing
  vitest: ^2.0.0

  # Type definitions
  '@types/node': ^22.0.0
  '@types/express': ^4.17.21
  '@types/pg': ^8.15.5
  '@types/jest': ^29.5.12
  '@types/prettier': 2.6.0
